apiVersion: v1
appVersion: "0.2.0"
description: Inspect HTTP requests. Debug webhooks
name: requestbin
version: 0.1.0
homepage: https://github.com/rbino/mfpb
sources:
  - https://github.com/rbino/mfpb
